import React from "react";
import { Scale, BookOpen, AlertCircle, Zap, ShieldCheck, Mail, Gavel } from "lucide-react";

export const metadata = {
  title: "Terms of Service | RecipeoAI - Global User Agreement",
  description: "Official terms and conditions for using RecipeoAI's AI-powered kitchen services. Updated March 2026.",
};

export default function TermsPage() {
  const lastUpdated = "March 22, 2026";

  return (
    <div className="min-h-screen bg-stone-50 text-stone-900 selection:bg-orange-100 pb-20">
      
      {/* --- HERO SECTION --- */}
      <section className="pt-32 pb-16 px-4 bg-white border-b border-stone-200">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-stone-900 text-stone-50 rounded-full text-xs font-bold mb-6 uppercase tracking-widest">
            <Gavel className="w-4 h-4 text-orange-500" /> User Agreement 2026
          </div>
          <h1 className="text-5xl md:text-7xl font-black mb-6 tracking-tighter">
            Terms of <span className="text-orange-600">Service</span>
          </h1>
          <p className="text-stone-500 text-lg font-light max-w-2xl mx-auto leading-relaxed">
            Please read these terms carefully before using RecipeoAI. By accessing our platform, 
            you agree to be bound by these global standards of service.
          </p>
          <div className="mt-8 p-4 bg-stone-100 rounded-2xl inline-block text-sm font-bold text-stone-500">
            Last Updated: {lastUpdated}
          </div>
        </div>
      </section>

      {/* --- CONTENT SECTION --- */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto space-y-12">
          
          {/* 1. Acceptance of Terms */}
          <section className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm">
            <div className="flex items-center gap-4 mb-6 text-orange-600">
              <Scale className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">1. Acceptance</h2>
            </div>
            <p className="text-lg text-stone-600 leading-relaxed font-light">
              By accessing or using RecipeoAI (the "Service"), you agree to comply with and be bound by these Terms of Service. If you do not agree, you must immediately cease all use of our platform. Our service is available to users globally, subject to local laws.
            </p>
          </section>

          {/* 2. AI Content & Usage */}
          <section className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm">
            <div className="flex items-center gap-4 mb-6 text-orange-600">
              <Zap className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">2. AI-Generated Output</h2>
            </div>
            <div className="space-y-4 text-stone-600 text-lg font-light">
              <p>All recipes and cooking instructions are generated by Artificial Intelligence. You acknowledge that:</p>
              <ul className="list-disc ml-5 space-y-2 text-sm md:text-base">
                <li>AI output may contain inaccuracies or unsafe suggestions.</li>
                <li>RecipeoAI is for informational purposes and does not constitute professional culinary or medical advice.</li>
                <li>Users are responsible for verifying ingredient safety, allergens, and cooking temperatures.</li>
              </ul>
            </div>
          </section>

          {/* 3. Subscriptions & Billing (Stripe) */}
          <section className="bg-stone-900 p-10 rounded-[2.5rem] text-stone-50 shadow-xl relative overflow-hidden">
             <div className="absolute top-0 right-0 w-64 h-64 bg-orange-600/10 blur-[100px] rounded-full"></div>
             <div className="relative z-10">
                <div className="flex items-center gap-4 mb-6">
                  <ShieldCheck className="w-8 h-8 text-orange-500" />
                  <h2 className="text-3xl font-bold tracking-tight italic">3. Payments & Billing</h2>
                </div>
                <p className="text-stone-400 text-lg leading-relaxed font-light mb-6">
                  Our Pro features (Head Chef Plan) are processed securely via **Stripe**. By subscribing, you agree to provide valid payment information and authorize us to charge the applicable fees.
                </p>
                <div className="p-6 bg-white/5 rounded-2xl border border-white/10 text-sm italic">
                  "All payments are handled with 256-bit encryption. Refund requests are subject to our refund policy and local consumer protection laws."
                </div>
             </div>
          </section>

          {/* 4. User Conduct & Content */}
          <section className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm">
            <div className="flex items-center gap-4 mb-6 text-orange-600">
              <BookOpen className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">4. Prohibited Actions</h2>
            </div>
            <p className="text-lg text-stone-600 leading-relaxed font-light mb-6">
              You agree NOT to use the Service for any illegal purpose, including but not limited to:
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm font-medium text-stone-500">
              <div className="p-4 bg-stone-50 rounded-xl border border-stone-100">• Hacking or data scraping</div>
              <div className="p-4 bg-stone-50 rounded-xl border border-stone-100">• Uploading non-food related content</div>
              <div className="p-4 bg-stone-50 rounded-xl border border-stone-100">• Attempting to bypass Pro features</div>
              <div className="p-4 bg-stone-50 rounded-xl border border-stone-100">• Harassing other users</div>
            </div>
          </section>

          {/* 5. Limitation of Liability */}
          <section className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm">
            <div className="flex items-center gap-4 mb-6 text-red-500">
              <AlertCircle className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">5. Limitation of Liability</h2>
            </div>
            <p className="text-lg text-stone-600 leading-relaxed font-light">
              To the maximum extent permitted by law, RecipeoAI and its developer Manish Singh shall not be liable for any indirect, incidental, special, or consequential damages resulting from your use of the service, including food poisoning, kitchen injuries, or hardware damage.
            </p>
          </section>

          {/* 6. Contact for Legal Matters */}
          <section className="py-12 border-t border-stone-200 text-center">
            <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center mx-auto mb-6 shadow-sm border border-stone-100">
              <Mail className="w-6 h-6 text-stone-300" />
            </div>
            <h2 className="text-2xl font-bold mb-4">Questions?</h2>
            <p className="text-stone-500 font-light mb-8">For any legal inquiries regarding these terms, please contact us at:</p>
            <a 
              href="mailto:legal@recipeoai.com" 
              className="inline-block bg-orange-600 text-white px-10 py-5 rounded-2xl font-bold hover:bg-stone-900 transition-all active:scale-95 shadow-lg shadow-orange-100"
            >
              legal@recipeoai.com
            </a>
          </section>

        </div>
      </section>

      {/* --- BRAND FOOTER --- */}
      <div className="text-center py-10 opacity-30 text-[10px] uppercase tracking-[0.8em] font-black italic">
        RecipeoAI Governance Framework • Global Ed. 2026
      </div>
    </div>
  );
}