import React from "react";
import { AlertTriangle, ShieldAlert, HeartPulse, Info, Scale, ExternalLink } from "lucide-react";

export const metadata = {
  title: "Legal Disclaimer | RecipeoAI - AI Accuracy & Health Safety",
  description: "Important legal information regarding AI-generated recipes, nutritional data, and food safety on RecipeoAI.",
};

export default function DisclaimerPage() {
  const lastUpdated = "March 22, 2026";

  return (
    <div className="min-h-screen bg-stone-50 text-stone-900 selection:bg-orange-100 pb-20">
      
      {/* --- HERO SECTION --- */}
      <section className="pt-32 pb-16 px-4 bg-white border-b border-stone-200">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 px-4 py-2 bg-red-50 text-red-600 rounded-full text-sm font-bold mb-6 border border-red-100 uppercase tracking-widest">
            <ShieldAlert className="w-4 h-4" /> Legal Protection Notice
          </div>
          <h1 className="text-5xl md:text-7xl font-black mb-6 tracking-tighter">
            Legal <span className="text-orange-600">Disclaimer</span>
          </h1>
          <p className="text-stone-500 text-lg font-light">
            Last Revised: <span className="font-bold text-stone-900">{lastUpdated}</span>
          </p>
        </div>
      </section>

      {/* --- CONTENT SECTION --- */}
      <section className="py-16 px-4">
        <div className="max-w-4xl mx-auto space-y-10">
          
          {/* 1. AI Content Disclaimer */}
          <div className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm transition-all hover:shadow-md">
            <div className="flex items-center gap-4 mb-6 text-orange-600">
              <AlertTriangle className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">AI-Generated Content</h2>
            </div>
            <p className="text-lg text-stone-600 leading-relaxed font-light">
              All recipes, cooking instructions, and ingredient suggestions provided by RecipeoAI are generated by Artificial Intelligence. While we strive for accuracy, AI models can occasionally produce incorrect, incomplete, or unsafe information. 
              <span className="block mt-4 font-bold text-stone-900 underline decoration-orange-300">
                Always use your personal judgment, check cooking temperatures, and ensure ingredients are fresh before consumption.
              </span>
            </p>
          </div>

          {/* 2. Health & Allergy Disclaimer */}
          <div className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm transition-all hover:shadow-md">
            <div className="flex items-center gap-4 mb-6 text-red-500">
              <HeartPulse className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">Health & Allergies</h2>
            </div>
            <div className="space-y-4 text-stone-600 text-lg font-light">
              <p>RecipeoAI is not a nutritionist or a medical professional. Any nutritional data (calories, macros) provided is an estimate only.</p>
              <p className="p-6 bg-red-50 rounded-2xl border border-red-100 text-red-800 text-sm font-medium">
                <strong>WARNING:</strong> If you have severe food allergies or medical dietary restrictions, do not rely solely on AI-generated recipes. Cross-check all ingredients with certified sources and manufacturers' labels.
              </p>
            </div>
          </div>

          {/* 3. No Liability */}
          <div className="bg-stone-900 p-10 rounded-[2.5rem] text-stone-50 shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-orange-600/10 blur-[100px] rounded-full"></div>
            <div className="relative z-10">
              <div className="flex items-center gap-4 mb-6">
                <Scale className="w-8 h-8 text-orange-500" />
                <h2 className="text-3xl font-bold tracking-tight italic">Limitation of Liability</h2>
              </div>
              <p className="text-stone-400 text-lg leading-relaxed font-light">
                Under no circumstances shall RecipeoAI, Manish Singh, or its affiliates be held liable for any damages, injuries, food-borne illnesses, or financial losses arising from the use of our recipes or AI suggestions. You use this platform at your own risk.
              </p>
            </div>
          </div>

          {/* 4. External Links Disclaimer (AdSense Requirement) */}
          <div className="bg-white p-10 rounded-[2.5rem] border border-stone-200 shadow-sm transition-all hover:shadow-md">
            <div className="flex items-center gap-4 mb-6 text-blue-500">
              <ExternalLink className="w-8 h-8" />
              <h2 className="text-3xl font-bold tracking-tight text-stone-900">External Links</h2>
            </div>
            <p className="text-lg text-stone-600 leading-relaxed font-light">
              Our website may contain links to third-party websites or services (such as affiliate links or advertisements). We do not guarantee the accuracy or safety of these external sites and are not responsible for their content or privacy practices.
            </p>
          </div>

          {/* 5. Final Contact Section */}
          <div className="py-12 text-center border-t border-stone-200">
            <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center mx-auto mb-6 shadow-sm">
              <Info className="w-8 h-8 text-stone-300" />
            </div>
            <h2 className="text-2xl font-bold mb-4">Legal Inquiries</h2>
            <p className="text-stone-500 font-light mb-8">If you have any questions regarding this Disclaimer, please contact our legal team.</p>
            <a 
              href="mailto:legal@recipeoai.com" 
              className="inline-block bg-orange-600 text-white px-10 py-5 rounded-2xl font-bold hover:bg-orange-700 transition-all active:scale-95 shadow-lg shadow-orange-100"
            >
              legal@recipeoai.com
            </a>
          </div>

        </div>
      </section>

      {/* --- BRAND FOOTER --- */}
      <div className="text-center py-10 opacity-30 text-xs uppercase tracking-[0.5em] font-black italic">
        RecipeoAI Compliance Standards 2026
      </div>
    </div>
  );
}